author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Develop: /develop/
 Diary: /diary/
 Archive: /archive/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
#  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "Software Developer"
  github_username: Zeniuus

experience:
  Classum:
    period: Mar. 2018 ~ Current
    position: Backend Developer
    description:
      - Firebase functions with TypeScript
  SPARCS:
    period: Mar. 2017 ~ Current
    position: Developer
    description:
      - Product manager of several projects (Zabo, newAra)
      - Git, Node.js, JavaScript seminars
  Lendit:
    period: Jan. 2018 ~ Feb. 2018
    position: Developer Intern
    description:
      - Several tools used internally
      - Code snippet manager
  KIXLAB:
    period: Jul. 2017 ~ Aug. 2018
    position: Research Intern
    description:
      - Asynchronous-interactive feedback interface

skill:
  Frontend:
    Vue.js: Intermediate
  Backend:
    Node.js: Beginner ~ Intermediate
    MongoDB: Beginner
    Spring Boot: Beginner
    Django: Beginner
  Language:
    JavaScript: Intermediate
    TypeScript: Beginner
    Java: Beginner
    Python: Beginner
  Else:
    AWS: Once

education: placeholder

projects: placeholder

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
